### ISSUE TITLE
[Feature Request] `retry_policy` on `continue_as_new`

### ISSUE THREAD

**Issue by patte** [temporalio/sdk-python#103]
### Is your feature request related to a problem? Please describe.

From https://github.com/temporalio/sdk-java/issues/1200 and https://github.com/temporalio/sdk-java/issues/1201:
> Right now continueAsNew is implemented in a way that assumes that most parameters are carried over by the server if not specified on the continueAsNew request. While in fact, it's the opposite. Server doesn't carry over most parameters.

If in the following code:
- raise on `iteration == 0`: The workflow is run (retried) 3 time before ending with `FAILD` (retryState: `MaximumAttemptsReached`)
- raise on `iteration == 1`: The workflow runs one time successfully `Continued as New`. The next run it ends with `Failed` (retryState: `RetryPolicyNotSet`).

I'd expect the workflow to retry 3 time before giving up.

```python
import asyncio
import logging
from dataclasses import dataclass
from typing import NoReturn
from datetime import timedelta

from temporalio import workflow, activity
from temporalio.client import Client
from temporalio.worker import Worker
from temporalio.common import RetryPolicy

@dataclass
class ComposeGreetingInput:
    greeting: str
    name: str

@activity.defn
async def compose_greeting(input: ComposeGreetingInput) -> NoReturn:
    # Always raise exception
    raise RuntimeError(f"Greeting exception: {input.greeting}, {input.name}!")


@workflow.defn(name="LoopingWorkflow")
class LoopingWorkflow:
    @workflow.run
    async def run(self, iteration: int) -> None:
        if iteration == 40:
            return
        workflow.logger.info("Running workflow iteration %s", iteration)
        await asyncio.sleep(1)
        
        # on which iteration to raise
        if (iteration == 0):
            await workflow.execute_activity(
                compose_greeting,
                ComposeGreetingInput("Hello", f"{iteration}"),
                start_to_close_timeout=timedelta(seconds=10),
                retry_policy=RetryPolicy(maximum_attempts=1),
            )

        workflow.continue_as_new(
            iteration + 1,
            #TypeError: continue_as_new() got an unexpected keyword argument 'retry_policy'
            #retry_policy=RetryPolicy(maximum_attempts=3),
        )



async def main():
    # Enable logging for this sample
    logging.basicConfig(level=logging.INFO)

    # Start client
    client = await Client.connect("localhost:7233")

    # Run a worker for the workflow
    async with Worker(
        client,
        task_queue="hello-continue-as-new-task-queue",
        workflows=[LoopingWorkflow],
        activities=[compose_greeting],
    ):

        await client.start_workflow(
            "LoopingWorkflow",
            0,
            id="hello-continue-as-new-workflow-id",
            task_queue="hello-continue-as-new-task-queue",
            retry_policy=RetryPolicy(maximum_attempts=3),
        )

        await asyncio.Future()


if __name__ == "__main__":
    asyncio.run(main())

```

### Describe the solution you'd like

The real solution might be for temporal server to carry over workflow options on continue_as_new. For the time being, we could work around it by adding `retry_policy` to `continue_as_new` (similar to `search_attributes`).

**Comment by cretz** [comment]
Thanks for the report! I have opened an issue to first implement this in our shared core code at https://github.com/temporalio/sdk-core/issues/372 and then we can implement in Python. I will update when complete.
