### ISSUE TITLE
[Bug] Search attributes require specific non-documented format

### ISSUE THREAD

**Issue by adrianbeloqui** [temporalio/sdk-python#116]
### What are you really trying to do?

I am writing some example workflows and activities to test the capabilities of this library. As I was doing so, while trying to execute a child flow with the `search_attributes` parameter set and after trying many times and getting an exception every time I decided to try the exact example on https://github.com/temporalio/samples-python/blob/main/hello/hello_search_attributes.py and that worked. So, trying a bit more I realized that it seems like the format of the key of the search attribute must be title cased or it won't work.

### Describe the bug

Setting `search_attributes` with keys that are not title case fails with the below trace stack.

```bash
2022-08-29 21:33:02,745 - ERROR - Failed completing activation on workflow with run ID 79534a74-5e75-4f51-9ff4-a77bdfac8196
Traceback (most recent call last):
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/worker/workflow.py", line 215, in _handle_activation
    await self._bridge_worker().complete_workflow_activation(completion)
  File "/home/vscode/.cache/pypoetry/virtualenvs/temporal-python--nLrvWXT-py3.10/lib/python3.10/site-packages/temporalio/bridge/worker.py", line 76, in complete_workflow_activation
    await self._ref.complete_workflow_activation(comp.SerializeToString())
RuntimeError: Completion failure: Unhandled grpc error when completing workflow task: Status { code: InvalidArgument, message: "BadSearchAttributes: search attribute customKeywordField is not defined", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
```

### Minimal Reproduction

```python
await workflow.execute_child_workflow(
            "ChildWorkflow",
            {"arg1": 1, "arg2": 2},
            id="child-workflow-1",
            task_timeout=timedelta(seconds=120),
            retry_policy=RetryPolicy(
                backoff_coefficient=2.0,
                maximum_interval=timedelta(seconds=120),
                maximum_attempts=5,
                non_retryable_error_types=["MyCustomNonRetriableException"],
            ),
            search_attributes={"customKeywordField": ["old-value"], "another_format":[""]},
)
```

### Environment/Versions

- OS and processor: Mac running Colima
- Temporal Version: `temporalio = "^0.1b1"`
- Are you using Docker or Kubernetes or building Temporal from source?  Using Temporal's docker-compose provided environment. Executing workflow from a VSCode Dev Container using Python 3.10.6

### Additional context

Nothing to add at this point

**Comment by adrianbeloqui** [comment]
This might not be a bug. This might be my own misinterpretation of the search attributes and how they work.

**Comment by cretz** [comment]
> So, trying a bit more I realized that it seems like the format of the key of the search attribute must be title cased or it won't work.

I think this depends on what the registered search attribute is. We do have default search attributes pre-registered like `CustomKeywordField` which appears pascal-cased, but that doesn't mean you can't register your own snake-cased name I believe. You can only set search attributes which have been registered/created on the server. See https://docs.temporal.io/tctl/admin/cluster/add-search-attributes for how to do this with the `tctl` CLI tool. If you run into any trouble with this, feel free to contact us on Slack or the forum.

**Comment by adrianbeloqui** [comment]
Hi @cretz, thank you for point me into the right direction, I was able to figure out. I can safely say that this feature to the extent I have tested it works well so I am going to close this issue.
