### ISSUE TITLE
Update Python proto library to latest

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#123]
### Is your feature request related to a problem? Please describe.

Currently we're on 3.x because `grpcio` package which we support as optional requires 3.x. But Pulumi seems to allow both: https://github.com/pulumi/pulumi/blob/master/sdk/python/requirements.txt. See if we can too. There is also (intentionally unlinked) PR 30382 on https://github.com/grpc/grpc that may let us upgrade.

**Comment by brightsparc** [comment]
Note the gRPC version that this library currently targets is `^1.48.0` however there is a [known memory leak](https://github.com/grpc/grpc/issues/28513) for `>=1.43.0` so suggest until this has been resolved pinning the gRPC dependency to `1.41.0` which is know to be stable.

**Comment by bergundy** [comment]
We don't invoke grpc directly from Python, it all goes through Rust Core using tonic so I this memory leak probably doesn't apply to this SDK.
