### ISSUE TITLE
Add support for Pydantic's secret types

### ISSUE THREAD

**Issue by averri** [temporalio/sdk-python#128]
### Is your feature request related to a problem? Please describe.

I would like to suggest adding support for serializing/deserializing Pydantic's secret types, like `SecretStr` and `SecretField`.
More information at: https://pydantic-docs.helpmanual.io/usage/types/#secret-types

### Describe the solution you'd like

Considering that Temporal logs all input and output arguments of activities and workflows, this is considered a security issue when sensitive information is present. Sensitive information must be protected from viewing in the Temporal UI and in the log files. The Pydantic's secret types already work fine with standard logging, but they fail to work with Temporal Python SDK because some SDK components do not know how to serialize/deserialize the secret types.

**Comment by cretz** [comment]
Temporal is a general purpose system and it does not currently have a way to exclude certain pieces of a payload from visualizing in the UI. This is not Python specific.

If you want data to be hidden from Temporal, we suggest end-to-end encryption. I am actively working on https://github.com/temporalio/samples-python/issues/5 to show how to do this in Python. But there is no way to say you only want some nested part of some payload to be hidden in some cases across languages but still exist as visible in the DB.

**Comment by averri** [comment]
That is the purpose of the `SecretStr` from Pydantic. If we use a class derived from `BaseModel` using fields of type `SecretStr`, those fields will appear in the Temporal UI with asterisks. See example:

```python
from pydantic import SecretStr, BaseModel
from hashlib import sha256

if __name__ == '__main__':

    class Signup(BaseModel):
        username: str
        clear_password: SecretStr

        @property
        def encrypted_password(self):
            return sha256(self.clear_password.get_secret_value().encode("utf-8")).hexdigest()


    class User(BaseModel):
        username: str
        encrypted_password: str


    signup = Signup(username="Alex", clear_password="12345678")

    print(f"Printing sensitive data: {signup}")

    # Using sensitive data, creating a user to store in the database.
    user = User(**signup.dict(), encrypted_password=signup.encrypted_password)

    print(f"user: {user}")
```

Running the above code produces:

```
signup: username='Alex' clear_password=SecretStr('**********')
user: username='Alex' encrypted_password='ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f'
```

We can see that no sensitive information appears in the logs, nor in the entities used to store information in the database (the `User` class can be used as a DB entity). This is just an example, in real apps, I also use the encrypted password as a `SecretStr`.

I have tested your other PR that fixes the support for Pydantic classes, it's working fine, it's just missing the Pydantic's secret types. 

As a workaround, I believe I can use a custom data converter. In the method `connect` of the `Client` class, there is a named argument called `data_converter`. Do you have an example of how to add the support for custom converters using this `data_converter`?

That example (https://github.com/temporalio/samples-python/issues/5) involving encryption is a great thing, thank you for that.

**Comment by cretz** [comment]
It only produces that in Python using Python constructs. The Temporal server is not written in Python and does not know anything about Pydantic or other Python-specific constructs. The way Temporal works is we serialize all input/output as JSON (usually). It is not specific to a language and many times users build things across languages. We do not have Temporal support for excluding specific parts of a payload currently.

You can't take the Pydantic/Python-specific things and apply them generically to the Temporal server or other languages. The input/output will be JSON that can be deserialized by all languages, so if you want a piece encrypted/hidden, you'll have to manually do so.

> Do you have an example of how to add the support for custom converters using this data_converter?

I do not have an example yet, I have created https://github.com/temporalio/samples-python/issues/15. Basically you'd create a custom payload converter that you'd either create a data converter with or add it to a composite payload converter on top of the existing ones.

**Comment by averri** [comment]
I am going to close this issue, as the solution for handling sensitive information in Temporal is to use the converters. Thanks for the https://github.com/temporalio/samples-python/issues/15.
