### ISSUE TITLE
[Feature Request] Extend readme contents about exception from activity

### ISSUE THREAD

**Issue by KMilhan** [temporalio/sdk-python#134]
### Is your feature request related to a problem? Please describe.

In [here](https://github.com/temporalio/sdk-python#exceptions), the project describes how the exception from workflows are handled.

Recently, I discovered many exceptions (such as `httpx` timeout) from activity create start_to_close timeout. I wish we have better documentation about the exception from activity side

### Describe the solution you'd like

Additional description about exceptions from the activity (worker) side. Which exception can we raise to mark it failed activity run and retry? what are not allowed exceptions?

**Comment by cretz** [comment]
Can you clarify the suggestion a bit?

> I discovered many exceptions (such as httpx timeout) from activity create start_to_close timeout

All exceptions from activities are treated equally (except for some special exceptions concerning cancellation and complete async). Not sure what you mean by "create start to close timeout" but the relation of timeouts/retries to errors are explained at https://docs.temporal.io/activities.

> Which exception can we raise to mark it failed activity run and retry?

All

> What are not allowed exceptions?

All exceptions are allowed. Can you clarify the question?

(also feel free to contact us on Slack at https://temporal.io/slack or the forum at https://community.temporal.io to get quicker answers)

**Comment by KMilhan** [comment]
Let me work on my side if I can reproduce the behavior I saw the last couple of weeks.

> All exceptions are allowed. Can you clarify the question?

In the current README,

it says

> Exceptions
> Workflows can raise exceptions to fail the workflow
> Using temporalio.exceptions.ApplicationError, exceptions can be marked as non-retryable or include details

I wanted to know what exceptions we can raise to mark the activity `failed` because I've seen activities left "stale" with the exception cases and Workflow has `ApplicationError` to officially mark it as failed workflow. Can we use this exception in activity too? or any exceptions are treated as failures?

So I thought maybe an exception explanation for the activities is "missing" by mistake. So I created this ticket.

Also, thank you for giving me the reference to the slack and community channel. I'll write questions on those channels.

**Comment by cretz** [comment]
> because I've seen activities left "stale" with the exception cases

There is no such thing as a "stale" activity. Are you sure it's not continually retrying? What does the UI show?

> Can we use this exception in activity too?

Yes, you can use the exception in activities too (it's good for passing details, setting type, and marking exceptions as not retryable)

> or any exceptions are treated as failures?

For activities, they are

> For activities, what's the exception that marks it "retryable" and what's the one that marks it "non-retryable"?

All are retryable by default except for 1) if you create `ApplicationError` with `non_retryable=True`, 2) the `retry_policy` set when you invoke the activity has a `non_retryable_error_types` that includes the unqualified name of the exception class (or application error `type`), or 3) the retry policy permits no more retries (i.e. max attempts has been reached; set it to 1 to disable retries).

> So I thought maybe an exception explanation for the activities is "missing" by mistake

:+1: I can make this section. Note, the README is not the canonical source of documentation, it's just there while the https://docs.temporal.io/application-development/ gets up to speed. The concept of activity failures/errors is not Python specific (though there are of course Python-specific parts). I will also submit a request to improve https://docs.temporal.io/application-development/foundations?lang=python#activity-execution and https://docs.temporal.io/activities/#activity-execution with regards to activity exceptions.

**Comment by KMilhan** [comment]
Thank you very much @cretz. In the UI, we had numerous activities reaching the max timeouts when the code raised an error (based on log), which looked like it didn't catch the exception as a failure but lost the activity worker.

I tried to reproduce the error but it seems like I can't with the minimal configuration. Seems like the issue was actually on our codebase side not on temporalio sides.

Also appreciate your consideration of adding readme section and guiding me to the resources.

Please feel free to close this ticket. Many thanks!

**Comment by cretz** [comment]
:+1: I have communicated with documentation to document errors properly for workflows and activities.

**Comment by yitian-reevo** [comment]
lol, a follow up question from year 2024, i think for latest version 1.8.0 (i may have an example), can you please take a look at this issue (https://github.com/temporalio/sdk-python/issues/679)? @cretz thanks!

I found no matter how I write, the activity are still being retried, no sure if it's our codebase problem.
