### ISSUE TITLE
[Feature Request] Better title and favicon for python.temporal.io

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-python#140]
This is what it currently looks like:

<img width="78" alt="image" src="https://user-images.githubusercontent.com/52304/191129217-d4307a97-46b7-4a97-8543-4d95184b4a55.png">

**Comment by cretz** [comment]
Am adding favicon but not altering title. It is not easy to do and it's basically just as good as others. Here is Python, TypeScript, Go, and Java:

![image](https://user-images.githubusercontent.com/206396/199794085-6a5e70e8-14fc-417a-ac35-6dcea5bec749.png)

Yes, Python is missing the suffix, but it's not worth the effort of a custom template.
