### ISSUE TITLE
Pydantic models with nested non-JSON-friendly field types cannot be serialized

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#143]
### What are you really trying to do?

Use this as a param:

```python
class MyClass(BaseModel):
   field_a: list[UUID]
```

### Describe the bug

Today we basically just call `dict()` on this which then tries to `json.dumps` that which it can't because that is _not_ a JSON-friendly dict. Unfortunately Pydantic does not provide a way to turn a model to a JSON-friendly dict. We cannot directly return the string result of `json()` in our encoder because we need it for nested purposes (i.e. `JSONEncoder.default`, _not_ `JSONEncoder.encode` which is only called at the top level, not nested).

The best solution right now I think is to accept anything that has a callable `json` attribute and invoke it, then turn it _back_ to Python object form via `json.loads`. This is the only easy way I am aware but has an obvious performance penalty. Was also mentioned at https://stackoverflow.com/questions/65622045/pydantic-convert-to-jsonable-dict-not-full-json-string.

**Comment by cretz** [comment]
Also see https://github.com/pydantic/pydantic/discussions/4456

**Comment by KMilhan** [comment]
Maybe we can add rather optimized json implementation such as`orjson` as an additional dependency and let the users utilize it if the performance penalty is the concern?
At least in my situation, json performance penalty has way lower priority than the developer's productivity. Ofc this can vastly vary case by case.

**Comment by cretz** [comment]
We are working hard to make the SDK flexible enough to use your own dependencies but not force too many dependencies on people. If you want to use `orjson`, you can create your own payload converter. https://github.com/temporalio/samples-python/tree/main/custom_converter is an example of adding a new converter, but you can do similar except replace the default converter set when creating a composite converter to change the last converter (which is `JSONPlainPayloadConverter`) with your own.

**Comment by cretz** [comment]
I am still gathering feedback on whether we accept the perf penalty of using `json()` instead of `dict()` (only to parse it back again). If Pydantic had `json_dict()` this would be no problem.

Until we either choose to support stringified JSON in models or Pydantic adds support for JSON-able dicts, a custom converter can be used.

**Comment by cretz** [comment]
After team discussion what we'll do is:

* Add support for `UUID` and maybe a couple of other types at https://pydantic-docs.helpmanual.io/usage/types/, but not ambiguous ones like `datetime` (yet, even though it can be argued ISO 8601 is _close_ to universal)
* Do not support `json()` from Pydantic models so we don't have to parse right back out to dict for nested use. Rather we will wait until Pydantic supports JSON-able dicts.
* Add a sample with easy to take code to allow _all_ Pydantic models to work via the slower JSON string approach
