### ISSUE TITLE
[Bug] Potential issue with parallel activities

### ISSUE THREAD

**Issue by nediamond** [temporalio/sdk-python#150]
### What are you really trying to do?

I am trying to execute activities in parallel with retries disabled, following the pattern from [this example](https://github.com/temporalio/samples-python/blob/main/hello/hello_parallel_activity.py)

When one activity execution fails, I would expect that successful activity completions are still saved to workflow history

### Describe the bug

I am observing that when an activity from the `asyncio.gather(` fails, it then fails the workflow & causes the remaining activity results to be dropped / not saved to workflow history.

It also gives this warning on subsequent activity completion after the initial failure:
```
WARN temporal_sdk_core::worker::activities: Activity not found on completion. This may happen if the activity has already been cancelled but completed anyway., task_token: TaskToken(CiQwNmI4MTAyZC02NzUzLTQxODctYjI3My1jNDVkMzVhOGIxMGESEXdlaWJvLXByb2ZpbGUtNTk3GiQ5ODdlMjAxMy0yNGYwLTRiMmMtOGFhNi1lODUyMjIxMjE5NGMgEygBMgE1Qgxwcm9jZXNzX2l0ZW1KCAgBEMWAQBgB), details: Status { code: NotFound, message: "workflow execution already completed", details: b"\x08\x05\x12$workflow execution already completed\x1aB\n@type.googleapis.com/temporal.api.errordetails.v1.NotFoundFailure", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
```

In Temporal UI, this presents as having both `ActivityTaskFailed` and `WorkflowExecutionFailed` in the event history but many pending activities are still listed indefinitely at the top.

### Minimal Reproduction
Based on https://github.com/temporalio/samples-python/blob/main/hello/hello_parallel_activity.py
Disabled retries, increased activity duration, added failing activity
```
import asyncio
from datetime import timedelta
from typing import List

from temporalio import activity, workflow
from temporalio.client import Client
from temporalio.common import RetryPolicy
from temporalio.worker import Worker


NO_RETRY = RetryPolicy(maximum_attempts=1)


@activity.defn
async def say_hello_activity(name: str) -> str:
    await asyncio.sleep(20)
    return f"Hello, {name}!"


@activity.defn
async def bad_activity() -> str:
    return 1/0


@workflow.defn
class SayHelloWorkflow:
    @workflow.run
    async def run(self) -> List[str]:
        # Run 5 activities at the same time
        results = await asyncio.gather(
            workflow.execute_activity(
                bad_activity, retry_policy=NO_RETRY, start_to_close_timeout=timedelta(minutes=20)
            ),
            workflow.execute_activity(
                say_hello_activity, "user2", retry_policy=NO_RETRY, start_to_close_timeout=timedelta(minutes=20)
            ),
            workflow.execute_activity(
                say_hello_activity, "user3", retry_policy=NO_RETRY, start_to_close_timeout=timedelta(minutes=20)
            ),
            workflow.execute_activity(
                say_hello_activity, "user4", retry_policy=NO_RETRY, start_to_close_timeout=timedelta(minutes=20)
            ),
            workflow.execute_activity(
                say_hello_activity, "user5", retry_policy=NO_RETRY, start_to_close_timeout=timedelta(minutes=20)
            ),
        )
        # Sort the results because they can complete in any order
        return list(sorted(results))


async def main():
    # Start client
    client = await Client.connect("temporal:7233")

    # Run a worker for the workflow
    async with Worker(
        client,
        task_queue="hello-parallel-activity-task-queue",
        workflows=[SayHelloWorkflow],
        activities=[say_hello_activity, bad_activity],
    ):

        # While the worker is running, use the client to run the workflow and
        # print out its result. Note, in many production setups, the client
        # would be in a completely separate process from the worker.
        result = await client.execute_workflow(
            SayHelloWorkflow.run,
            id="hello-parallel-activity-workflow-id",
            task_queue="hello-parallel-activity-task-queue",
        )
        print(f"Result: {result}")


if __name__ == "__main__":
    asyncio.run(main())

```

### Environment/Versions

- i9 Mac
- Temporal Version: docker image `temporalio/auto-setup:1.18.0` 
- Running using docker compose

### Additional context

- Noticed when doing the minimal reproduction that activity latency is a significant factor

**Comment by cretz** [comment]
> When one activity execution fails, I would expect that successful activity completions are still saved to workflow history

When a workflow completes, all activities are cancelled. This is Temporal server behavior. The workflow is complete when an exception is thrown out of it. I think that WARN may be ignored, but I will check with that team (and we'll lower the log level if so).

From https://docs.python.org/3/library/asyncio-task.html#asyncio.gather:

> If return_exceptions is False (default), the first raised exception is immediately propagated to the task that awaits on gather().

This means in your code, while all 5 activities may start, `bad_activity` will raise, causing `gather` to raise, causing the workflow to complete with a failure, causing all other activities and anything outstanding on the workflow to be cancelled.

**Comment by nediamond** [comment]
>>If return_exceptions is False (default), the first raised exception is immediately propagated to the task that awaits on gather().

>This means in your code, while all 5 activities may start, bad_activity will raise, causing gather to raise, causing the workflow to complete with a failure, causing all other activities and anything outstanding on the workflow to be "cancelled".

Ah I tried that option earlier but think I ruled it out quickly out of confusion - definitely seems appropriate. Thanks!
