### ISSUE TITLE
[Feature Request] Rework search attributes and add list endpoint to client

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#153]
### Describe the solution you'd like

* Need to support individual, per-type search attributes and only allow collections for keywords
* Expose workflow listing API on client which should be a lazy iterator

See https://github.com/temporalio/proposals/pull/67

**Comment by cretz** [comment]
This was solved in #158

**Comment by cretz** [comment]
(accidentally closed, reopened)

**Comment by bergundy** [comment]
@cretz this should still be open, we need to rework search attributes too.

**Comment by cretz** [comment]
Sorry, I said I reopened but I never did

**Comment by cretz** [comment]
This is now a duplicate of #381 (and #366)
