### ISSUE TITLE
[Feature Request] Integration test for Otel gRPC metrics collector

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#157]
### Describe the solution you'd like

Confirm the Otel gRPC URL format (and if possible whether it works over TLS) via integration test

**Comment by nrhodes** [comment]
Copied from the [slack thread](https://temporalio.slack.com/archives/CTT84RS0P/p1665750534907139?thread_ts=1665697686.033889&cid=CTT84RS0P):
I modified the `hello_activity.py` sample in the `sample-python` repo to add a call to `init_telemetry`, specifying a localhost endpoint as follows:
```
async def main():
    # Uncomment the line below to see logging
    #logging.basicConfig(level=logging.DEBUG)
    open_telemetry_config = OtelCollectorConfig(
            url="localhost:9999", headers={
            }
        )
    init_telemetry(
        TelemetryConfig(
        otel_metrics=open_telemetry_config,
        otel_tracing=open_telemetry_config,
        )
    )
    # Start client
    client = await Client.connect("localhost:7233")
    # Run a worker for the workflow
    async with Worker(
        client,
        task_queue="hello-activity-task-queue",
        workflows=[GreetingWorkflow],
        activities=[compose_greeting],
    ):
        # While the worker is running, use the client to run the workflow and
        # print out its result. Note, in many production setups, the client
        # would be in a completely separate process from the worker.
        result = await client.execute_workflow(
            GreetingWorkflow.run,
            "World",
            id="hello-activity-workflow-id",
            task_queue="hello-activity-task-queue",
        )
        print(f"Result: {result}")

```

I then checked with Wireshark and saw that there were no connections being made to port 9999 on the loopback interface. There were connections to the temporal server at 7233, as I’d expect.

**Comment by cretz** [comment]
There's not a good way to put an integration test for the collector side in the primary SDK repo, so I added it to the PR at https://github.com/temporalio/samples-python/pull/18.

The issue here I think is that you have to use a real URL like `http://localhost:9999`.
