### ISSUE TITLE
[Feature Request] Support patch search attribute

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#194]
### Describe the solution you'd like

TBD. Go puts `TemporalChangeVersion` key with a list of strings like `"<changeid>-<version>"` for every version seen. What do we want to do here? cc @bergundy

**Comment by bergundy** [comment]
Reuse the same search attribute and use patch id for the value

**Comment by bergundy** [comment]
I'd want us to buffer all of the search attribute updates and emit a single upsert command at the end of the activation like we discussed in the TS search attributes proposal: https://github.com/temporalio/proposals/pull/67/files#diff-7d87e4d9af7e84955486e56bc4d577483f5fa34479dbe84b2ceeb50f4d64a81cR31
We should try and get this in for beta 3 to avoid another history incompatible change.

**Comment by cretz** [comment]
@bergundy - This also kinda overlaps with #153. Do you also want to revisit how we do search attributes (singular vs list) at this time too? Do we have a devised API there? I see we even added a new type in https://github.com/temporalio/api/pull/248. I can at least change the types to the expected, but we still have to support lists of all forms for older stuff. Should I try to at least solve the singular-search-attribute problem now or no?

**Comment by cretz** [comment]
> I'd want us to buffer all of the search attribute updates and emit a single upsert command at the end of the activation like we discussed in the TS search attributes proposal:

Also, can you clarify in that proposal when we shouldn't send the update? If an exception is caused that causes workflow task failure, does that mean my pending search attributes are not persisted yet? But an exception that would just cause workflow failure I do send the pending update, but of course before the failure?

Also, what if I have an activity that uses the client to check search attributes of the calling workflow? Can I guarantee that an upsert search attribute command after a schedule activity command will always persist the values before an activity started? Can I even guarantee that today if upsert search attribute is in order? (I will ask server team)

**Comment by bergundy** [comment]
No commands are sent on WFT failure so I don't think there's an issue here.
All commands should be handled in atomically on the server, the ordering shouldn't matter for correctness here.

**Comment by cretz** [comment]
> the ordering shouldn't matter for correctness here.

Except workflow completion/failed/cancelled which I think we have to flush before that

**Comment by cretz** [comment]
This is being done in core not lang.
