### ISSUE TITLE
[Bug] Identity equality for int enum fails inside sandbox

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#200]
### Describe the bug

When a `is` check is done on a type like `IntEnum` that comes as a workflow arg, it fails because the arg conversion uses the type from the definition type hint which is technically different than the type _inside_ the sandbox. This may also occur on `isinstance` for data classes, need to check.

Not exactly sure what to do here. Maybe re-reference the full type's qualified name when converting instead of reusing the type hint itself?

**Comment by bergundy** [comment]
We've had similar issues in TS when passing around object between v8 contexts.
Our solution was to instantiate everything in the proper context but I understand that's not feasible with the Python sandboxing approach.

**Comment by cretz** [comment]
It might be feasible. I have the qualified name, so I can re-reference it. Will have to see.
