### ISSUE TITLE
[Feature Request] Integration in django application

### ISSUE THREAD

**Issue by AdrianPardo99** [temporalio/sdk-python#211]
### Is your feature request related to a problem? Please describe.

I want to implement a worker in my django app but I don't found how to implemented

### Additional context

I use zappa for async task, but my manager assign to me change all zappa async task to temporal io workflows and activities, so I deploy and test a temporal server on my docker instances, but when i tried to export my envars and my settings there is no much friendly for integrate my worker or my temporal client.

**Comment by cretz** [comment]
There is no one way to integrate Temporal into your existing Python project. Temporal uses asyncio. Integrate it like you would any asyncio software. You can start the worker on app startup in an `async def` with `asyncio.run()`. Or maybe you want your worker to be in a separate process from your web app which is common.

As for using the client in Django app, please refer to Django documentation on how to make async calls.

For general help, feel free to join us on Slack at https://temporal.io/slack or our forums at https://community.temporal.io.

**Comment by AdrianPardo99** [comment]
@cretz ok tnx, I'll check if this sdk can integrate in future in another project.

**Comment by cretz** [comment]
Let us know in forum or Slack if you have other questions regarding this integration
