### ISSUE TITLE
[Bug] Python 3.11 TypeError: Passing coroutines is forbidden, use tasks explicitly.

### ISSUE THREAD

**Issue by AndrewIngram** [temporalio/sdk-python#232]
The following lines of code run without issue in Python 3.10, but throw in 3.11:

```python
await asyncio.wait(
    [asyncio.sleep((snooze_until - now).total_seconds()), self._is_reopened.wait()],
    return_when=asyncio.FIRST_COMPLETED,
)
```

(this is similar to an example in the readme, so it seems idiomatic)

The error I get in 3.11 is `TypeError: Passing coroutines is forbidden, use tasks explicitly.`

Encountered on the `python:3.11-slim` Docker image, initially using `temporalio=0.1b3`, reproduced on `0.1b4` 

I think the relevant Python docs are https://docs.python.org/3/library/asyncio-task.html#waiting-primitives

> Passing coroutine objects to wait() directly is forbidden

Not sure if I'd class it as a bug, as the change in Python appears to be deliberate, but it means the canonical way to solve this in Temporal might now be different?

**Comment by cretz** [comment]
This is a known Python change and unrelated to Temporal. Why use wait with a sleep instead of just sleep? Also, when using wait, you need a task. So use create_task or similar.

I will update the README to use tasks.

**Comment by AndrewIngram** [comment]
I'm not sure I understand your question, I want to wait for a specific time, or an event, whichever happens first.

But I hit the same issue even without the sleep and just using wait on the event (as per the readme example), so i'm keen to see what the canonical way of doing this is -- i'd been assuming it was what's in the readme.

**Comment by cretz** [comment]
Sorry, my mobile phone cut off the right part, I see the event wait now.

The proper way since Python 3.11 is to use tasks (so wrap your pieces in create_task). We just haven't updates the README yet. This isn't not Temporal specific, you'd do the same thing using normal asyncio in Python 3.11.

**Comment by AndrewIngram** [comment]
Do you mean like this (which seems to work in 3.11)?

```python
try:
    await asyncio.wait_for(
        self._is_reopened.wait(), timeout=(snooze_until - now).total_seconds()
    )
except TimeoutError:
    pass
```

**Comment by AndrewIngram** [comment]
Do you want me to leave this open so you can track the readme change, or close it?

**Comment by cretz** [comment]
That wait_for example looks fine. Yes you can leave this open for me to update the README.

The best practice is to use asyncio in Temporal like you would outside of Temporal.

**Comment by AndrewIngram** [comment]
Easier said then done when this is our first time using async Python in anger after a 15+ years of non-async Python :)
