### ISSUE TITLE
[Feature Request] Support JSON Type Converters

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#264]
### Is your feature request related to a problem? Please describe.

People need to customize `temporal.converters.value_to_type` for use with their types during JSON conversion

### Describe the solution you'd like

Add a `JSONTypeConverter` ABC that converts to and from a user type to JSON-able type. Change `JSONPlainPayloadConverter` to accept a collection of these and make that easier to set in construction of default payload converter.

**Comment by michael-cybrid** [comment]
Big 👍 from us on this.

We have conversion working  [OpenAPI generated models](https://github.com/OpenAPITools/openapi-generator) working by inheriting from `JSONPlainPayloadConverter` and doing something like the following but it has limitations (around optional and collections, etc.) and first party support would be awesome:

```python
 def from_payload(
        self,
        payload: Payload,
        type_hint: Type[Any] | None = None,
    ) -> Any:
        """See base class."""
        try:
            obj = json.loads(payload.data, cls=self._decoder)
            if type_hint:
                if service_one.is_openapi_model_subclass(type_hint):
                    obj = service_one.dict_to_model(obj, type_hint)

                elif service_two.is_openapi_model_subclass(type_hint):
                    obj = service_two.dict_to_model(obj, type_hint)

                else:
                    obj = value_to_type(type_hint, obj)
            return obj
        except json.JSONDecodeError as err:  # pragma: no cover
            raise RuntimeError("Failed parsing") from err
```

**Comment by cretz** [comment]
> it has limitations (around optional and collections, etc.) 

@michael-cybrid - I think for custom input/output types it can be clearer to use your own encoding payload converter with your own encoding (e.g. `json/open-api`) instead of reusing the existing encoding. This makes it more portable/obvious to other Temporal clients/users that custom logic is needed. Granted I understand this doesn't help with collections and such, but usually you know which types you need to support for your own conversion.

Regardless, I have just opened a PR for JSON type converters and README updates that can help your use case if reusing existing JSON conversion logic.
