### ISSUE TITLE
Temporal CLI based ephemeral server

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-python#272]

**Comment by bergundy** [comment]
Depends on https://github.com/temporalio/sdk-core/issues/485

Consider maintaining support for Temporalite for a while.

**Comment by cretz** [comment]
This is also needed for some patch fixes that use the SDK metadata field not present in older Temporalite

**Comment by cretz** [comment]
Make sure to accept additional namespaces here beyond the primary one.

**Comment by cretz** [comment]
This cannot be done until https://github.com/temporalio/temporal/pull/4317 is in the Temporal CLI
