### ISSUE TITLE
mutate workflow instance attributes from within activities that it executes

### ISSUE THREAD

**Issue by AmirRezaSobhdel** [temporalio/sdk-python#274]
I have a **state_dict** instance attribute in my WorkFlow class and I want it to be passed as an argument to the activity to then be updated in the activity like this :

```
    @activity.defn
    async def compose_greeting(name, state) -> str:
        state['running_activity'] = "name_of_this_activity"
        return name
```
```
    @workflow.defn
    class GreetingWorkflow(BaseWorkflow):
        def __init__(self):
            self.state_dict = dict()
        @workflow.run
        async def run(self) -> str:
            res = await workflow.execute_activity(
                compose_greeting,
                args=['amirreza', self.state],
                start_to_close_timeout=timedelta(seconds=10),
            )
            print(self.state_dict)
            return res
```

but it appears that the argument pass of the state_dict is not reference-based and the changes I make to it in the activity, won't apply to the **self.state_dict** inside the WorkFlow class.

how can I get this to work?

My final purpose is to create a BaseActivity class which my callable activity classes inherit this `state['running_activity'] = "name_of_this_activity"` functionality from and update the **self.state_dict** when they are executed.

**Comment by cretz** [comment]
This cannot be done. Activities may not even run on the same machine. Activities and workflows are intentionally completely separate things that run in separate place that serialize the data sent between them.

If you want to relay information back to the workflow from the activity, you can do it via the return value or via signals.

**Comment by cretz** [comment]
Closing issue as it was just a question
