### ISSUE TITLE
[Feature Request] Access to invoking workflow in activity method

### ISSUE THREAD

**Issue by bbkgh** [temporalio/sdk-python#275]
Hi. Is there any way to access invoking workflow in activity?
sth like:
```
    @activity.defn
    async def compose_greeting() -> str:
        print(workflow.name)
```

**Comment by cretz** [comment]
You can call [temporalio.activity.info()](https://python.temporal.io/temporalio.activity.html#info) which returns an [Info](https://python.temporal.io/temporalio.activity.Info.html) class containing information about the activity including workflow information.

**Comment by cretz** [comment]
Closing issue as it was just a question
