### ISSUE TITLE
types-protobuf dependency is still on 3.x, while package supports protobuf 4.x

### ISSUE THREAD

**Issue by schibrikov** [temporalio/sdk-python#277]
Hi, the title says it all.
The problem with types-protobuf 3.x for me is this issue https://github.com/python/typeshed/issues/5800.
In short: using types-protobuf 3.x overrides google cloud SDK typings, so I want to upgrade.

Can we change 
```
protobuf = ">=3.20"
types-protobuf = "~3.20"
```
to
```
protobuf = ">=3.20"
types-protobuf = ">=3.20"
```
?

**Comment by cretz** [comment]
Definitely can change that. I should have done so when backporting this library to work with proto 3.x library. Feel free to PR or wait a bit and I'll get to it. Thanks for the report!

**Comment by schibrikov** [comment]
Good, I guess I'll try to make a PR
