### ISSUE TITLE
[Feature Request] Validate type of timedelta() parameters in validate methods?

### ISSUE THREAD

**Issue by mbernier** [temporalio/sdk-python#312]
### Is your feature request related to a problem? Please describe.

When writing a RetryPolicy, I got an error
```
File "/opt/homebrew/lib/python3.10/site-packages/temporalio/client.py", line 407, in start_workflow
    return await self._impl.start_workflow(
  File "/opt/homebrew/lib/python3.10/site-packages/temporalio/client.py", line 2352, in start_workflow
    input.retry_policy.apply_to_proto(req.retry_policy)
  File "/opt/homebrew/lib/python3.10/site-packages/temporalio/common.py", line 75, in apply_to_proto
    self._validate()
  File "/opt/homebrew/lib/python3.10/site-packages/temporalio/common.py", line 96, in _validate
    if self.maximum_interval.total_seconds() < 0:
```
which is due to the fact that I forgot to wrap my interval as a timedelta rather than as an integer.

### Describe the solution you'd like

In the validate methods, such as [temporalio/common:line 75](https://github.com/temporalio/sdk-python/blob/main/temporalio/common.py#L86) - we could test the type of the parameters that should be timedeltas, to make sure - then throw an error to say something similar to "You passed an integer, but timedelta was expected, see this line of the README for more information ___" 

### Additional context

This would increase the developer experience, because customers can quickly get to the correct answer due to the error informing them of what is missing.

**Comment by cretz** [comment]
I think it's a bit unreasonable to check the types of the hundreds of parameters we have at runtime. We offer type hints and strongly encourage the use of MyPy or similar. This same issue exists when using JS with our TypeScript SDK. If you are choosing to not use the typing facilities, it's a bit much to have us check them all at runtime.

**Comment by cretz** [comment]
Closing as not reasonable to check parameters' types at runtime. The existing Python tooling is built to catch these before runtime.
