### ISSUE TITLE
[Bug] Retry Policy on start_workflow

### ISSUE THREAD

**Issue by mbernier** [temporalio/sdk-python#313]
### What are you really trying to do?

I initially was trying to restrict a retry policy to have a maximum interval of 5 seconds with a coefficient of 1x.

### Describe the bug

When retry policy is passed on start_workflow, the behavior of the retry is that it keeps doubling and the max_interval is not respected.

### Minimal Reproduction

```
retryPolicy = RetryPolicy(
            initial_interval=timedelta(minutes=2),
            backoff_coefficient=float(1.0),
            maximum_interval=timedelta(minutes=50),
            maximum_attempts=4
        )

workflow_handle = await temporal_client.start_workflow(
    MyWorkflow.run,
    id="my-workflow-2",
    task_queue="default",
    retry_policy=retryPolicy
)
await workflow_handle.result()
```

### Environment/Versions

Name: temporalio
Version: 1.1.0

Python: 3.10

OS: Mac OSX Ventura 13.2.1

**Comment by cretz** [comment]
Closing as unable to replicate and weeks without original opener response
