### ISSUE TITLE
[Bug] await call in async query function would cause the function to return immediately and cause an error on client side

### ISSUE THREAD

**Issue by orby-will** [temporalio/sdk-python#317]
### What are you really trying to do?

Use "await" in workflow.query decorated async function. In the SDK documentation, it clearly says that the async function is expected. If async functions are expected, I assume that I should be able to expect await to work properly

### Describe the bug

Await call in async query function would cause the function to return immediately and cause an error on the client side.

Code:

>     @workflow.query
>     async def get_suggestion(self) -> str:
>         await workflow.wait_condition(
>             lambda: self.orbflow.suggested_action != "" or self._exit.is_set())
>         return self.orbflow.suggested_action

Error Msg and Stack Trace

> Traceback (most recent call last):
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/service.py", line 723, in _rpc_call
>     resp = await client.call(
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/bridge/client.py", line 126, in call
>     result = await resp_fut
> temporal_sdk_bridge.RPCError: (3, 'Query response was empty', b'\x08\x03\x12\x18Query response was empty\x1aE\nCtype.googleapis.com/temporal.api.errordetails.v1.QueryFailedFailure')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/client.py", line 2465, in query_workflow
>     resp = await self._client.workflow_service.query_workflow(
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/service.py", line 658, in __call__
>     return await self.service_client._rpc_call(
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/service.py", line 738, in _rpc_call
>     raise RPCError(message, RPCStatusCode(status), details)
> temporalio.service.RPCError: Query response was empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/Users/ldxstc/orby/automl/scripts/run_workflow_orbot.py", line 166, in main
>     await browser_loop(crawler, workflow_handle)
>   File "/Users/ldxstc/orby/automl/scripts/run_workflow_orbot.py", line 94, in browser_loop
>     gpt_action = await workflow_handle.query(
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/client.py", line 1240, in query
>     return await self._client._impl.query_workflow(
>   File "/Users/ldxstc/orby/automl/env/lib/python3.10/site-packages/temporalio/client.py", line 2472, in query_workflow
>     raise WorkflowQueryFailedError(err.message)
> temporalio.client.WorkflowQueryFailedError: Query response was empty

### Minimal Reproduction
>     @workflow.query
>     async def get_suggestion(self) -> str:
>         await asyncio.sleep(1)
>         return self.orbflow.suggested_action

### Environment/Versions

- OS and processor: M1 Mac,
- Temporal Version: temporalio==1.0.0
- Are you using Docker or Kubernetes or building Temporal from source? -> docker

**Comment by cretz** [comment]
Queries need to be read-only with no side effects, so they should never await on anything Temporal. Ideally you would not use an async query function, but we made it available because there are plenty of Python async def functions that are still side-effect free. In other SDKs we disallow async queries to prevent users from doing what you're doing.

You started a timer in a query which is disallowed. If/when we get a static analyzer, it would catch things like this. In the meantime, refer to https://docs.temporal.io/workflows#query:

> A Query must never mutate the state of the Workflow Execution—that is, Queries are read-only and cannot contain any blocking code. This means, for example, that Query handling logic cannot schedule Activity Executions.

Or in this case, timers. We can probably add more docs in the README to make this clearer.

**Comment by cretz** [comment]
Closing as question. Just because `async def` allowed for query doesn't mean query can do async _workflow_ calls, just that if there is a Python library being used in a query function with a fast async call it will work.

**Comment by orby-will** [comment]
Thanks for replying. But can you please explain more about why "starting a timer" mutates a workflow state?

How about waiting for a state to become true, such as "await workflow.wait_condition(xxx)"? It does not work either. How is it mutating the state of a workflow?
