### ISSUE TITLE
[Bug] Python generics for function type hints

### ISSUE THREAD

**Issue by cloud-sauce** [temporalio/sdk-python#322]
### What are you really trying to do?

I would like to have a generic container that is used as the type hint for workload and activity functions, for example,

```python
from dataclasses import dataclass
from typing import Generic, TypeVar

VariableType = TypeVar("VariableType")


@dataclass
class MyContainer(Generic[VariableType]):
    common: int
    variable: VariableType
```

### Describe the bug

When a generic container is used the following issue occurs,

```
Traceback (most recent call last):
  File "/home/.../.cache/pypoetry/virtualenvs/temporalio-samples-XXX-py3.10/lib/python3.10/site-packages/temporalio/worker/_activity.py", line 350, in _run_activity
    else await self._data_converter.decode(
  File "/home/.../.cache/pypoetry/virtualenvs/temporalio-samples-XXX-py3.10/lib/python3.10/site-packages/temporalio/converter.py", line 1000, in decode
    return self.payload_converter.from_payloads(payloads, type_hints)
  File "/home/.../.cache/pypoetry/virtualenvs/temporalio-samples-XXX-py3.10/lib/python3.10/site-packages/temporalio/converter.py", line 246, in from_payloads
    values.append(converter.from_payload(payload, type_hint))
  File "/home/.../.cache/pypoetry/virtualenvs/temporalio-samples-XXX-py3.10/lib/python3.10/site-packages/temporalio/converter.py", line 508, in from_payload
    obj = value_to_type(type_hint, obj, self._custom_type_converters)
  File "/home/.../.cache/pypoetry/virtualenvs/temporalio-samples-XXX-py3.10/lib/python3.10/site-packages/temporalio/converter.py", line 1394, in value_to_type
    raise TypeError(f"Unserializable type during conversion: {hint}")
TypeError: Unserializable type during conversion: __main__.ComposeGreetingInput[int]
```

### Minimal Reproduction

The error can be reproduced using the [`hello_activity`](https://github.com/temporalio/samples-python/blob/main/hello/hello_activity.py) example with the modifications,

```python
from typing import Generic, TypeVar

BonusType = TypeVar("BonusType")


@dataclass
class ComposeGreetingInput(Generic[BonusType]):
    greeting: str
    name: str
    bonus: BonusType


# Basic activity that logs and does string concatenation
@activity.defn
async def compose_greeting(input: ComposeGreetingInput[int]) -> str:
    activity.logger.info("Running activity with parameter %s" % input)
    return f"{input.greeting}, {input.name}! Bonus info: {input.bonus}"


# Basic workflow that logs and invokes an activity
@workflow.defn
class GreetingWorkflow:
    @workflow.run
    async def run(self, name: str) -> str:
        workflow.logger.info("Running workflow with parameter %s" % name)
        return await workflow.execute_activity(
            compose_greeting,
            ComposeGreetingInput("Hello", name, 123),
            start_to_close_timeout=timedelta(seconds=10),
        )
```

### Environment/Versions

- OS and processor: WSL (Ubuntu 20.04 LTS)
- Temporal Version: Python SDK version `1.2.0` and services [from template](https://github.com/temporalio/docker-compose/blob/main/docker-compose-cass-es.yml) (`1.20.2`)
- Are you using **Docker** or Kubernetes or building Temporal from source? (Docker compose)

### Additional context

I realize the problem could be solved by child class definitions with static type hints, ex.

```python
@dataclass
class IntegerGreeting(ComposeGreetingInput):
    bonus: int


# Basic activity that logs and does string concatenation
@activity.defn
async def compose_greeting(input: IntegerGreeting) -> str:
```

but it would be very nice to be able to use generic typing

**Comment by cretz** [comment]
From the README:

> Classes with generics may not have the generics properly resolved. The current implementation, similar to Pydantic, does not have generic type resolution. Users should use concrete types.

It is much too complicated to solve this with any kind of consistency. We would request you make specific non-generic concrete dataclasses for specific use cases instead of reusing/creating generic ones.

**Comment by cloud-sauce** [comment]
What about adding a flag that would *allow* generics, but only support JSON-serializable types for them? For example, `BonusType` (from above) would be restricted to `float`, `int`, `string`, or `bool`. 

Or is there a comment or documentation around what the underlying issue with allowing them is? Is it a problem with accessing the type hinted class in the consumer? I'm interested in better understanding the limitation, if you don't mind

**Comment by cretz** [comment]
It's not that we _couldn't_ do it, it's that there is limited benefit.

The main limitation is that such limited support adds limited value and more confusion (the next issue will be opened asking why we don't support other generic ways and so on ad infinitum). You can just as easily create specialized data classes for the few primitives needed rather than altering the SDK to support such a limited subset of generics. We also encourage people to build dataclasses specifically for Temporal use instead of trying to reuse other ones that may not have the same constraints (e.g. JSON serializable, prefer smaller in size, etc).

If it were hard to create non-generic forms of these models, it'd be worth implementing. Similarly if Python had a built in way to serialize dataclasses to/from JSON with generic support we'd be happy to reuse it as we do in SDK languages where that exists.

**Comment by cretz** [comment]
Closing as intentionally unsupported (and documented as such)
