### ISSUE TITLE
[Bug] Wrong types when using "workflow.unsafe.imports_passed_through"

### ISSUE THREAD

**Issue by masylum** [temporalio/sdk-python#338]
### What are you really trying to do?

When I need to import activities for a given workflow, the type system fails to recognize the activity type.

### Describe the bug

I'm currently using pyright and it tells me that the `activity` parameter when calling `workflow.execute_activity` should be a string. It's doing so because it does not match any of the overloads. When I bring the activity to the same file (so I bypass the `workflow.unsafe.imports_passed_through`) then the type system is happy

### Minimal Reproduction

I will use a simplified example from the README:

```py
# activities.py
from temporalio import activity

@activity.defn
async def say_hello(name: str) -> str:
    return f"Hello, {name}!"

# workflow.py
from temporalio import workflow

# Import our activity, passing it through the sandbox
with workflow.unsafe.imports_passed_through():
    from .activities import say_hello

@workflow.defn
class SayHello:
    @workflow.run
    async def run(self, name: str) -> str:
        return await workflow.execute_activity(
            say_hello, name
```

This makes pyright complain:

```
Argument of type "Module("say_hello") | ((params: str) -> Coroutine[Any, Any, str])" cannot be assigned to parameter "activity" of type "str" in function "execute_activity"
Type "Module("say_hello") | ((params: str) -> Coroutine[Any, Any, str])" cannot be assigned to type "str"
Type "Module("say_hello")" cannot be assigned to type "str" [reportGeneralTypeIssues]
```

### Environment/Versions

Python 3.11.4

**Comment by masylum** [comment]
hmm... Honestly, I've treid to setup nvim with mypy and I failed miserably. Feel free to close it if that's just a pyright bug

**Comment by cretz** [comment]
I am not sure it is a PyRight bug specifically, but yes, if you cannot replicate except with PyRight it might be a PyRight bug worth submitting to them.
