### ISSUE TITLE
Publish to pip

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [temporalio/sdk-python#36]
Hi, congrats on the progress, this is amazing. I've seen you published this package to pypi once in the past. Would you mind publishing it once more ? We need it currently in my team to experiment, but having to build everything from scratch is not ideal to integrate in our main repo.

**Comment by cretz** [comment]
Yes, I have or two more issues to solve, then I'll publish.

**Comment by cretz** [comment]
This has been published
