### ISSUE TITLE
[Bug] Temporal graceful shutdown does not prevent activity failure

### ISSUE THREAD

**Issue by jayfjin** [temporalio/sdk-python#367]
### What are you really trying to do?
We have a long running activity and would like for it not to be retried upon a rolling restart of our worker fleet.

### Describe the bug

Despite setting graceful_shutdown_timeout=timedelta(minutes=20), we still see our activity fail once SIGTERM is issued.

### Minimal Reproduction
1. Set up a long running activity and a worker processing it
2. Send SIGTERM to that worker

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 1.1.0
- Building the sdk from source, then packaging our own docker container and running on k8s

### Additional context

Based upon my reading of the code, I suspect the graceful_shutdown_timeout option isn't actually doing anything: https://github.com/temporalio/sdk-python/blob/main/temporalio/worker/_worker.py#L436

However, I didn't do a super deep dive on this so could definitely be wrong. 

If there was a way to suspend polling in python at the worker level, that would be great too - and we could implement our own signal handler. worker.suspendpolling appears to be available for go/java temporal sdk.

**Comment by cretz** [comment]
> we still see our activity fail once SIGTERM is issued.

Are you calling `shutdown()` on the worker? That's what stops polling and waits graceful time before cancelling activities.

> If there was a way to suspend polling in python at the worker level, that would be great too

This is what `shutdown()` does. It stops polling, notifies all activities of worker shutdown (there are things on the activity module that can be checked), waits the graceful timeout, then forcefully cancels activities.

See https://github.com/temporalio/sdk-python#worker-shutdown.

**Comment by jayfjin** [comment]
Interesting, yes that was also tried with a SIGTERM handler, but after reading the docs now I suspect our implementation of that was flawed - thanks.

**Comment by cretz** [comment]
(feel free to reopen or join us on Slack if still not working for you)
