### ISSUE TITLE
[Bug] Client stuck connecting or starting a workflow

### ISSUE THREAD

**Issue by AsiPanda** [temporalio/sdk-python#385]
### What are you really trying to do?

To create a second client in a different process (i.e. in gunicorn).

### Describe the bug

The client randomly hangs during `connect` of a client in a new process, after another client was created in the current process.

### Minimal Reproduction

<details><summary>Code from a modified sample</summary>

```python
import asyncio
import logging
from dataclasses import dataclass
from datetime import timedelta

from temporalio import activity, workflow
from temporalio.client import Client
from temporalio.runtime import Runtime, TelemetryConfig
from temporalio.worker import Worker


# While we could use multiple parameters in the activity, Temporal strongly
# encourages using a single dataclass instead which can have fields added to it
# in a backwards-compatible way.
@dataclass
class ComposeGreetingInput:
    greeting: str
    name: str


# Basic activity that logs and does string concatenation
@activity.defn
async def compose_greeting(input: ComposeGreetingInput) -> str:
    activity.logger.info("Running activity with parameter %s" % input)
    return f"{input.greeting}, {input.name}!"


# Basic workflow that logs and invokes an activity
@workflow.defn
class GreetingWorkflow:
    @workflow.run
    async def run(self, name: str) -> str:
        workflow.logger.info("Running workflow with parameter %s" % name)
        return await workflow.execute_activity(
            compose_greeting,
            ComposeGreetingInput("Hello", name),
            start_to_close_timeout=timedelta(seconds=10),
        )


async def run_workflow():
    logging.debug("Creating a temporal client")
    client = await Client.connect("localhost:7233", runtime=Runtime(telemetry=TelemetryConfig()))
    res = await client.execute_workflow(
        GreetingWorkflow.run,
        "World",
        id="hello-activity-workflow-id",
        task_queue="hello-activity-task-queue",
    )
    logging.debug(f"Result: {res}")


async def worker():
    client = await Client.connect("localhost:7233")
    worker = Worker(
        client,
        task_queue="hello-activity-task-queue",
        workflows=[GreetingWorkflow],
        activities=[compose_greeting],
        debug_mode=True,
    )
    await worker.run()


async def main():
    from multiprocessing import Process

    # Uncomment the line below to see logging
    logging.basicConfig(level=logging.DEBUG)

    worker_process = Process(target=lambda: asyncio.run(worker()))
    worker_process.start()

    # While the worker is running, use the client to run the workflow and
    # print out its result. Note, in many production setups, the client
    # would be in a completely separate process from the worker.
    await run_workflow()
    p = Process(target=lambda: asyncio.run(run_workflow()))
    p.start()
    p.join()
    worker_process.terminate()


if __name__ == "__main__":
    asyncio.run(main())

````

</details>

### Environment/Versions

- OS and processor: Fedora 38, Ryzen 7 PRO 6850U
- Temporal Version: Python SDK 1.3.0, Temporal 1.22.0
- Are you using Docker or Kubernetes or building Temporal from source? Yes, the *auto-setup* docker image

### Additional context

The client usually hangs in `temporalio.bridge.client.py:78` at `temporalio.bridge.temporal_sdk_bridge.connect_client`.

**Comment by cretz** [comment]
> To create a second client in a different process (i.e. in gunicorn).

Does this mean in a post-forked process? The SDK does not work with forking at this time (#11). It would be a challenge to share the Rust runtime across forks properly/safely.

**Comment by AsiPanda** [comment]
Yes it does, I haven't found this limitation anywhere in the Temporal.io documentation and thought that it could be solved by passing a new Runtime instance to the Client.connect method. Is this not the case? What exactly does a Runtime object represent?

**Comment by cretz** [comment]
> I haven't found this limitation anywhere in the Temporal.io documentation

:+1: We will add documentation for this

> thought that it could be solved by passing a new Runtime instance to the Client.connect method. Is this not the case? What exactly does a Runtime object represent?

No it cannot be solved that way. A runtime represents a Rust Tokio thread pool and runtime (see https://github.com/tokio-rs/tokio/issues/1541 and similar).
