### ISSUE TITLE
[Bug] Fix lint warnings for Client.execute_workflow

### ISSUE THREAD

**Issue by lethe3000** [temporalio/sdk-python#444]
### What are you really trying to do?

Execute a workflow using python sdk: client.execute_workflow

### Describe the bug

I followed tutorial: Build a data pipeline Workflow with Temporal and Python with code
```
stories = await client.execute_workflow(
        TemporalCommunityWorkflow.run,
        id="temporal-community-workflow",
        task_queue=TASK_QUEUE_NAME,
    )
```
 but got lint warnings as below:

```
Unexpected type(s):(() -> Coroutine[Any, Any, list[TemporalCommunityPost]], str, Any)Possible type(s):(MethodAsyncNoParam[SelfType, ReturnType], str, str)(str, str, str)
```

### Environment/Versions

- OS and processor: Mac intel
- Temporal python sdk: 1.4.0
- IDE: Pycharm CE

**Comment by cretz** [comment]
Assuming the workflow properly doesn't have any parameters, I wonder if Pycharm is the problem here and not Temporal. Can you confirm this same issue happens with other type checkers like MyPy and Pyright/vscode?

**Comment by lethe3000** [comment]
> Assuming the workflow properly doesn't have any parameters, I wonder if Pycharm is the problem here and not Temporal. Can you confirm this same issue happens with other type checkers like MyPy and Pyright/vscode?

I tested my code with pyright, no issues reported, it should be a Pycharm issue.

**Comment by cretz** [comment]
:+1: Closing issue. May be worth opening an issue there. We test with MyPy in our CI, but we don't have one for a specific IDE.
