### ISSUE TITLE
[Bug] Cut a new release please

### ISSUE THREAD

**Issue by arlyon** [temporalio/sdk-python#448]
### What are you really trying to do?

Let me just prefix this as this is a raw stream of consciousness to help illustrate the perspective of an outside user. Thanks for all the great work you guys do (especially how open it is) :heart: 

Hello, this was my experience trying to update temporal to 1.4.0 and noticing all my pytest tests failing (since it fails tests with deprecation warnings by default) due to typed search attributes

https://github.com/temporalio/features/issues/336#issuecomment-1855475624

### Describe the bug

After running around trying to find an example to update my code, I ended up hitting a bug that was fixed in https://github.com/temporalio/sdk-python/commit/6f966c7ca59d01c02243561d186867e199f252a6

### Minimal Reproduction

N/A

### Environment/Versions
N/A

### Additional context

Updating the python samples and a longer transition period before marking old apis as deprecated would be nice. Even just one release to massage any bugs. Now I have a half migrated codebase which is just annoying.

**Comment by cretz** [comment]
1.5.0 was released
