### ISSUE TITLE
pathlib RestrictedWorkflowAccessError

### ISSUE THREAD

**Issue by vamsu** [temporalio/sdk-python#450]
### What are you really trying to do?

Execute a workflow 

### Describe the bug

Running into: Evicting workflow with run ID 2cc67004-c6a9-473b-bb84-78be1b3dad30, message: Workflow activation completion failed: Failure { failure: Some(Failure { message: \"Cannot access pathlib.Path.resolve.__call__ from inside a workflow. If this is code from a module not used in a workflow or known to only be used deterministically from a workflow, mark the import as pass through

So far, I tried the below, but no luck

```
with workflow.unsafe.imports_passed_through():
    import pathlib
```
anyway to disable the restrictions on sandbox and let the developers ensure deterministic behavior ?

**Comment by jackklika** [comment]
A quick fix if you don't mind the entire workflow being deterministic is to disable sandboxing on the entire workflow via `@workflow.defn(sandboxed=False)`.

**Comment by cretz** [comment]
> anyway to disable the restrictions on sandbox and let the developers ensure deterministic behavior ?

Sure, see the README: https://github.com/temporalio/sdk-python#avoiding-the-sandbox. You can:

```python
with temporalio.workflow.unsafe.sandbox_unrestricted():
    my_path.resolve();
```

But I would strongly discourage using disk-based calls from inside a workflow.

(closing issue as just a question, but feel free to keep responding here or join us on `#python-sdk` on Slack)
