### ISSUE TITLE
[Bug] Parent packages of a package are automatically imported via the Sandbox

### ISSUE THREAD

**Issue by rcomesan** [temporalio/sdk-python#453]
### What are you really trying to do?

I'm trying to import a workflow defined in a module placed in a nested package.

### Describe the bug

If I import my workflow using `from myapp.subpackage.workflows import MyWorkflow`, and `myapp` or `myapp.subpackage` imports non-deterministic libraries or modules that import non-deterministic libraries (e.g. httpx, torch), I get a `RuntimeError: Failed validating workflow {defn.name}`.

I'm expecting only the module `myapp.subpackage.workflows.__init__.py` that contains my deterministic code/classes to be imported via the sandbox. However, it seems that modules  `myapp.__init__.py`  and  `myapp.subpackage.__init__.py` also get imported somehow, and they break the sandbox as they contain non-deterministic code unrelated to workflows. 

### Minimal Reproduction

My repository contains 2 main files (main_failing.py and main_working.py) that illustrate this behavior.:
https://github.com/rcomesan/sandbox-intermediate-packages-repro/tree/main

### Environment/Versions

- Debian amd64
- Python 3.11.2
- Temporal SDK: 1.4.0
 - Docker image: temporalio/auto-setup:1.22.3

### Additional context
If I disable the sandbox either passing sandboxed=False to the decorator or at worker construction time using an UnsandboxedWorkflowRunner this behavior no longer occurs, and I'm able to start my workers without issues.

**Comment by cretz** [comment]
This is the proper behavior according to Python specification. From https://docs.python.org/3/reference/import.html#regular-packages:

> Importing `parent.one` will implicitly execute `parent/__init__.py` and `parent/one/__init__.py`.

We use normal `importlib` behavior by intention. Closing the issue as by intention, but feel free to continue discussion here or on `#python-sdk` on Slack.
