### ISSUE TITLE
[Feature Request] Reload client certificate 

### ISSUE THREAD

**Issue by pvcnt** [temporalio/sdk-python#512]
### Is your feature request related to a problem? Please describe.

I am connecting to a Temporal server with a client certificate, which is "short"-lived (a few days). When it expires, my client becomes unusable.

### Describe the solution you'd like

I need a way to refresh the certificate without restarting my entire client. For example, I would need to be able to specify a path to a certificate, or a function supplying a certificate in TLSConfig, instead of giving directly the certificate.

**Comment by cretz** [comment]
> I need a way to refresh the certificate without restarting my entire client

If you mean just change in the client, that is less reasonable because TLS establishment is done on connect, so you need to reconnect the client. But if you mean replace the client in the worker without restarting the worker, yes, this is something we are adding soon (I just opened #513 since I didn't see an original public issue on this).

**Comment by cretz** [comment]
Closing this issue in favor of #513 where we allow client replacement on long-running workers (which means it can be reconnected with a new cert). To use a new TLS certificate on a client, you have to reconnect a client.

**Comment by pvcnt** [comment]
Excellent, thank you!

**Comment by ankit-sultania** [comment]
Lets say my worker is running indefinitely with a client and after an hour the cert is rotated and I replace the worker client, but seems like that is not enough and I need to reconnect. Does it mean I need to kind of stop and start the worker? Like how do you reconnect the client without having to stop the worker that is already running?

**Comment by cretz** [comment]
You connect the client before replacing it on the worker. You set the `client` property on the worker (which has a [setter for `client` property](https://python.temporal.io/temporalio.worker.Worker.html#client)) to replace the client with a newly connected client. You do not have to stop the worker, the next time the worker issues requests it will start using the new client (but outstanding poll requests will still complete using the existing client).

**Comment by ankit-sultania** [comment]
Thanks for the explanation. So, you are saying that workers would be still be able to pull from the task queue after 1) certs are rotated and 2) the client is replaced with the new client. Correct?

**Comment by ankit-sultania** [comment]
Ok, now i see what's going on here. 1) bridge service client is extracted [here](https://github.com/temporalio/sdk-python/blob/main/temporalio/worker/_worker.py#L320) which is used for polling tasks 2) upon replacing the worker.client we also replace the bridge client under the hood [here](https://github.com/temporalio/sdk-python/blob/main/temporalio/worker/_worker.py#L566) which means this new bridge client is used for polling
