### ISSUE TITLE
[Feature Request] Update rustls and mio in Rust dependencies

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#520]
### Describe the solution you'd like

Even though we are unaffected by the vulnerabilities, security scans show our current rustls and mio versions as of this writing have vulnerabilities. Update them (and any other things as needed).

**Comment by bbemis017** [comment]
Can we also add H2 to this list of dependencies that need to be upgraded since GHSA-q6cp-qfwq-4gcv is flagging the h2 version the sdk currently uses

**Comment by bbemis017** [comment]
Are there any updates on when the next python sdk could be release to include the dependency updates?/

**Comment by cretz** [comment]
No updates here on specific release timelines, but hopefully soon.
