### ISSUE TITLE
Document workflow-friendly concurrency control

### ISSUE THREAD

**Issue by drewhoskins-temporal** [temporalio/sdk-python#554]
Document and add tests confirming that `asyncio.Lock` and `asyncio.Semaphore` can be used to control interleaving of signal and update handlers and the main workflow coroutine.

**Comment by sreeprasannar** [comment]
does this mean currently using `asyncio.Lock` could lead to a deadlock?

**Comment by dandavison** [comment]
Hi @sreeprasannar

> does this mean currently using asyncio.Lock could lead to a deadlock?

No -- using `asyncio.Lock` in `sdk-python` workflow code is appropriate and recommended.

Thanks! I've changed the title & wording of this ticket.

**Comment by drewhoskins-temporal** [comment]
https://github.com/temporalio/samples-python/pull/123
https://github.com/temporalio/documentation/pull/2959
