### ISSUE TITLE
[Feature Request] Propagate changes made with updated Rust dependencies

### ISSUE THREAD

**Issue by kelkawi-a** [temporalio/sdk-python#560]
### Is your feature request related to a problem? Please describe.

The changes in #520 have not yet propagated to `pip`, leading to the vulnerabilities previously identified to still exist in the latest version of the `temporalio` SDK. 

### Describe the solution you'd like

For the `temporalio` SDK installed using `pip` to have the latest Rust dependencies installed in #520 .

**Comment by cretz** [comment]
This will happen next release (should not be too long, but does not need to have a GH issue opened). In the meantime you can build and install the SDK itself.
