### ISSUE TITLE
[Bug] Workflow Task Timeout only supports upto 2 minutes

### ISSUE THREAD

**Issue by mrafay0** [temporalio/sdk-python#561]
### What are you really trying to do?

Trying to set task timeout for a workflow.

### Describe the bug

Can be less than 2 minutes but not more than that, is it expected?
### Minimal Reproduction

```
result = await temporal_client.execute_workflow(
               ....
                task_timeout=timedelta(seconds=60*15), # gets set to 2 minute instead of 15 minutes
)
```

![2024-06-25 at 21 35 26](https://github.com/temporalio/sdk-python/assets/168713959/70bb8671-f6e9-44b1-b400-3f0fa75c69d7)

**Comment by cretz** [comment]
This is the maximum timeout of this value as enforced on the server. It is unrelated to Python, see https://docs.temporal.io/encyclopedia/detecting-workflow-failures#workflow-task-timeout. Closing issue as by intention.

Note, it is usually a bad idea to change this value and if you're finding yourself changing it, there is likely something else wrong. Workflow tasks should only take milliseconds. Feel free to join us on #python-sdk in Slack at https://t.mp/slack or on the forums at https://community.temporal.io.
