### ISSUE TITLE
activity returning dict object forcefully

### ISSUE THREAD

**Issue by MaazBinMusa** [temporalio/sdk-python#578]
### Describe the bug

I have a workflow where I run 3 activities and I have defined dataclass types for each activity input output. The 3rd activity is acting uniquely strange, where eventhough I outline the activity to return a specific type of dataclass obj, it keeps returing the dict version of it.

I am forced to check after that activity if the obj is a dataclass instance or not, and if not, I have to make a new obj and initialize it with all the items in the dict that was returned.

### Additional context

I'm running the python version of temporal, on the cloud. We also have a codec server in the middle. I don't think the env has much to do with it since the first two activities work just fine but the last one is acting strange.

**Comment by cretz** [comment]
This is dependent upon how it is called in the workflow. The workflow `execute_activity` uses the activity's return type hint to know what to deserialize into, or if it doesn't have one, it just does default for JSON which is a `dict`. What does the signature of the activity look like and how are you calling it from a workflow?

(also, feel free to come join us on [Slack](https://t.mp/slack) in the `#python-sdk` channel for questions/help)

**Comment by MaazBinMusa** [comment]
@cretz thank you for the prompt attention.

This is how I call the activity in the workflow
```
post_process_dto = await workflow.execute_activity(
      activity=activity_name,
      arg=post_process_dto,
      start_to_close_timeout=timedelta(seconds=10),
  )
```

And this is the activity itself

```
async def postprocess_find_confidence(self, dto: PostAbstractionDTO) -> PostAbstractionDTO:
        return dto
```

**Comment by cretz** [comment]
If you call the activity via a string name, the code does not know the type to deserialize to, so it defaults to whatever JSON does (which is dict in this case). You should add `result_type=PostAbstractionDTO` or, even better, call it via `execute_activity_method(MyActivityClass.postprocess_find_confidence, ...`.

**Comment by MaazBinMusa** [comment]
specifying the return type fixed the issue 👍 Thankyou!
