### ISSUE TITLE
[Feature Request] Get workflow handle/send signals from non-async code

### ISSUE THREAD

**Issue by nathanielobrown** [temporalio/sdk-python#64]
### Is your feature request related to a problem? Please describe.
I have a non-async activity and I want to send signals to the parent workflow from this activity. I want to do this because I have existing code that scrapes websites and yields those results in a generator and I want to notify the parent workflow of those results as they are fetched. I would prefer not to convert the activity to async because:

1. The code the activity calls is not async and I don't want to convert it completely to async (it would ruin my tests requests mocking for one thing)
2. I'm nervous about executing my non-async code in a thread pool. I know there is already a threadpool, but spawning threadpools all over the place _feels_ like it could get out of control. Better to have one thread pool and be able to control it's size is my thought
3. If I convert to async code and run my sync code in a thread pool, I'd have to communicate generator results through a queue and it would be a complicated solution

### Describe the solution you'd like
Would it be possible to add synchronous versions of `workflow.get_external_workflow_handle_for` (not defined as async, but fails if called outside of async function) and `workflow_handle.signal`? In general I guess the question is, are the functions for interacting with workflows going to support use from non-async code?

I can imagine lots of future cases where I'll want to interact form non-async code as my database interactions are not async so lots of my code is not async.

### Additional context
Maybe there are some async patterns I can use to mitigate these issues (for example [asyncer](https://asyncer.tiangolo.com/)) but I have not had much luck so far. I'm not an async expert, so any advice would be appreciated.

**Comment by cretz** [comment]
> Would it be possible to add synchronous versions of workflow.get_external_workflow_handle_for (not defined as async, but fails if called outside of async function) and workflow_handle.signal?

I think there may be some confusion here. Everything in the `workflow` package is only for calling from inside the workflow. You would not use them for an activity. If you want to signal a workflow from an activity, you'd use a client. Activity code is just any regular Python code. 

(granted I need to solve #52 soon so you can have a callable class with the client as a class attribute, but you can create the client inside the activity as needed)

**Comment by nathanielobrown** [comment]
> I think there may be some confusion here. Everything in the `workflow` package is only for calling from inside the workflow. You would not use them for an activity. If you want to signal a workflow from an activity, you'd use a client. Activity code is just any regular Python code.

Ooh, OK. That makes sense and is an easy enough rule to remember. I guess something to highlight in the docs as that gets built out.

I have some thoughts on the callable class issue, I'll comment on that issue.

**Comment by cretz** [comment]
:+1: I will try to make it clearer at https://python.temporal.io/temporalio.workflow.html and once we get general purpose documentation (actively being worked on) I'll make sure it is clear there too.

**Comment by ofirsa** [comment]
Hi,
I’m facing the same situation as you described, meaning, I want to send a signal from a non async activity to the parent workflow.
Can you please how you solved the issue?
Thanks
