### ISSUE TITLE
[Feature Request] Support for test server without internet access

### ISSUE THREAD

**Issue by wilsoniya** [temporalio/sdk-python#681]
### Is your feature request related to a problem? Please describe.

I'm trying to run temporal workflow tests in an environment without access to the public internet. This means that `WorkflowEnvironment.start_time_skipping(...)` et. al. can't fetch the time skipping test server from temporal.download. 

There's a possible workaround I found while stepping through temporal-core-sdk in which I could e.g. make a [test server tarball](https://temporal.download/temporal-test-server/default?platform=linux&arch=amd64&sdk-version=default&sdk-name=temporal-test-server)  available on the air-gapped infrastructure, unpack it, then thread the path to the binary into my test harness and pass it as the `test_server_existing_path` to `WorkflowEnvironment.start_time_skipping`. But I wish a more ergonomic option existed, especially for a use case that might not be uncommon.

### Describe the solution you'd like

In order of descending convenience for my use case:

* be able to provide a URL of the tarball itself via environment variable (without the json info indirection); I'm able to cache the tarball at a different location
* be able to provide a URL of the test server binary via environment variable
* be able to provide an absolute path to the test server binary on disk via environment variable

Basically, configuration via environment variable saves having to thread information through to every WorkflowEnvironment instantiation.

It would also be helpful to document the location where test server binaries can be acquired. 

An alternative solution could be packaging and publishing platform/arch-specific pypi packages containing the test server. This could either be in the sdk-python package itself, or a separate package which is conditionally depended on by sdk-python via dependency group.

I'm def open to other approaches. Thanks!

### Additional context
* PR introducing on-demand test server fetching: https://github.com/temporalio/sdk-core/pull/389
* Call site where test server is downloaded: https://github.com/cretz/temporal-sdk-core/blob/3105ef349fe60265157ae7fa96674c964ae5c979/core/src/ephemeral_server/mod.rs#L298

**Comment by cretz** [comment]
> In order of descending convenience for my use case:

As mentioned there, we provide the option for you to give the executable path. This gives you full freedom without us being too specific. I would suggest if you want a URL-based download, you can use your preferred downloading tool/library to download it and extract the tarball. Same if it were on S3 or provided via some other method. Similarly if you want to have this option set via environment variable, just `test_server_existing_path=os.getenv('MY_ENV_VAR')`. 

I am not sure we want to bake in so many ways to get a file beyond the default/no-option and the advanced option.

**Comment by cretz** [comment]
> Is there documentation describing where to find the test server binary tarballs?

No, we can add this. Yeah they are part of https://github.com/temporalio/sdk-java releases

**Comment by Kilo59** [comment]
@cretz @wilsoniya 

Where can I find this documentation?

**Comment by cretz** [comment]
This documentation is in the API docs at https://python.temporal.io/temporalio.testing.WorkflowEnvironment.html#start_time_skipping:

> test_server_existing_path [...] Existing path to the test server binary. If present, no download will be attempted to fetch the binary.

Though your error looks like it's referring to `start_local`, so those are at https://python.temporal.io/temporalio.testing.WorkflowEnvironment.html#start_local. But I am afraid it, and many of the other advanced options there, are not (yet) documented outside of the API docs.

> Also can the error message here could be improved. At least logging or including the HTTP status code returned.

Yes, this is because the Rust HTTP request library does not include more detail from the inner message (https://github.com/seanmonstar/reqwest/blob/e2d4b14c695acaebe531af7ce4712e182278f38a/src/error.rs#L185). We can look into improving it.
