### ISSUE TITLE
Replayer

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#82]
### Describe the solution you'd like

Need workflow replayer (also includes history JSON parser/fixer)

**Comment by cretz** [comment]
Don't forget to add something to README about disabling deadlock detection.

**Comment by ccl0326** [comment]
Hi @cretz , what's the progress for replayer now? We want to use sdk-python in production, but  replayer is a blocking feature for production.

**Comment by cretz** [comment]
It is under active development in a branch on my fork. Hopefully a PR will be open soon.
